import 'package:vouch_v2/core/widgets/loaders/flickr_loader.dart';
import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import '../../../../core/theme/app_colors.dart';
import '../../../../core/theme/app_spacing.dart';
import '../../../../core/theme/app_text_styles.dart';
import '../../../campuses/models/campus_model.dart';
import '../../../campuses/providers/campus_provider.dart';

import 'package:image_picker/image_picker.dart';
import '../../../../core/providers/storage_provider.dart';

class CreateCampusModal extends ConsumerStatefulWidget {
  const CreateCampusModal({super.key});

  @override
  ConsumerState<CreateCampusModal> createState() => _CreateCampusModalState();
}

class _CreateCampusModalState extends ConsumerState<CreateCampusModal> {
  final _formKey = GlobalKey<FormState>();
  final _nameController = TextEditingController();
  final _locationController = TextEditingController();
  final _descriptionController = TextEditingController();
  bool _isLoading = false;
  XFile? _logoImage;
  XFile? _bannerImage;
  final ImagePicker _picker = ImagePicker();

  @override
  void dispose() {
    _nameController.dispose();
    _locationController.dispose();
    _descriptionController.dispose();
    super.dispose();
  }

  Future<void> _pickImage() async {
    final XFile? image = await _picker.pickImage(source: ImageSource.gallery);
    if (image != null) {
      final name = image.name.toLowerCase();
      if (!name.endsWith('.jpg') && 
          !name.endsWith('.jpeg') && 
          !name.endsWith('.png') && 
          !name.endsWith('.gif') && 
          !name.endsWith('.webp') && 
          !name.endsWith('.bmp')) {
        if (mounted) {
          ScaffoldMessenger.of(context).showSnackBar(
            const SnackBar(content: Text('Invalid file format. Please upload an image (JPG, PNG, WEBP, etc.)')),
          );
        }
        return;
      }
      setState(() {
        _logoImage = image;
      });
    }
  }

  Future<void> _pickBanner() async {
    final XFile? image = await _picker.pickImage(source: ImageSource.gallery);
    if (image != null) {
      final name = image.name.toLowerCase();
      if (!name.endsWith('.jpg') && 
          !name.endsWith('.jpeg') && 
          !name.endsWith('.png') && 
          !name.endsWith('.gif') && 
          !name.endsWith('.webp') && 
          !name.endsWith('.bmp')) {
        if (mounted) {
          ScaffoldMessenger.of(context).showSnackBar(
            const SnackBar(content: Text('Invalid file format. Please upload an image (JPG, PNG, WEBP, etc.)')),
          );
        }
        return;
      }
      setState(() {
        _bannerImage = image;
      });
    }
  }

  Future<void> _submit() async {
    if (!_formKey.currentState!.validate()) return;

    setState(() => _isLoading = true);
    try {
      String? logoUrl;
      if (_logoImage != null) {
        logoUrl = await ref.read(storageServiceProvider).uploadAcademicAsset(
          code: _nameController.text.trim(),
          file: _logoImage!,
          type: 'campus',
        );
      }

      String? bannerUrl;
      if (_bannerImage != null) {
        bannerUrl = await ref.read(storageServiceProvider).uploadAcademicAsset(
          code: _nameController.text.trim(),
          file: _bannerImage!,
          type: 'campus',
          isBanner: true,
        );
      }

      final campus = CampusModel(
        id: '', // Will be generated by Supabase
        name: _nameController.text.trim(),
        location: _locationController.text.trim(),
        description: _descriptionController.text.trim(),
        logoUrl: logoUrl,
        bannerUrl: bannerUrl,
      );

      await ref.read(campusesProvider.notifier).addCampus(campus);
      
      if (mounted) {
        Navigator.pop(context);
        ScaffoldMessenger.of(context).showSnackBar(
          const SnackBar(content: Text('Campus created successfully')),
        );
      }
    } catch (e) {
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(content: Text('Error creating campus: $e')),
        );
      }
    } finally {
      if (mounted) setState(() => _isLoading = false);
    }
  }

  @override
  Widget build(BuildContext context) {
    return Dialog(
      shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(24)),
      child: Container(
        width: 500,
        padding: const EdgeInsets.all(AppSpacing.xl),
        child: Form(
          key: _formKey,
          child: Column(
            mainAxisSize: MainAxisSize.min,
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              Row(
                mainAxisAlignment: MainAxisAlignment.spaceBetween,
                children: [
                  Text(
                    'Add New Campus',
                    style: AppTextStyles.titleLarge.copyWith(fontWeight: FontWeight.bold),
                  ),
                  IconButton(
                    onPressed: () => Navigator.pop(context),
                    icon: const Icon(Icons.close_rounded),
                  ),
                ],
              ),
              const SizedBox(height: AppSpacing.lg),
              Text(
                'Campus Name',
                style: AppTextStyles.labelMedium.copyWith(fontWeight: FontWeight.bold),
              ),
              const SizedBox(height: AppSpacing.xs),
              TextFormField(
                controller: _nameController,
                decoration: const InputDecoration(
                  hintText: 'e.g. DORSU Main Campus',
                ),
                validator: (val) => val == null || val.isEmpty ? 'Required' : null,
                enabled: !_isLoading,
              ),
              const SizedBox(height: AppSpacing.md),
              Text(
                'Location',
                style: AppTextStyles.labelMedium.copyWith(fontWeight: FontWeight.bold),
              ),
              const SizedBox(height: AppSpacing.xs),
              TextFormField(
                controller: _locationController,
                decoration: const InputDecoration(
                  hintText: 'e.g. Mati City, Davao Oriental',
                ),
                validator: (val) => val == null || val.isEmpty ? 'Required' : null,
                enabled: !_isLoading,
              ),
              const SizedBox(height: AppSpacing.md),
              Text(
                'Description (Optional)',
                style: AppTextStyles.labelMedium.copyWith(fontWeight: FontWeight.bold),
              ),
              const SizedBox(height: AppSpacing.xs),
              TextFormField(
                controller: _descriptionController,
                maxLines: 3,
                decoration: const InputDecoration(
                  hintText: 'Brief description of the campus...',
                ),
                enabled: !_isLoading,
              ),
              const SizedBox(height: AppSpacing.md),
              Text(
                'Campus Logo',
                style: AppTextStyles.labelMedium.copyWith(fontWeight: FontWeight.bold),
              ),
              const SizedBox(height: AppSpacing.xs),
              SizedBox(
                width: double.infinity,
                child: OutlinedButton.icon(
                  onPressed: _isLoading ? null : _pickImage,
                  icon: Icon(_logoImage != null ? Icons.check_circle_rounded : Icons.image_outlined, 
                    color: _logoImage != null ? Colors.green : null),
                  label: Text(_logoImage != null ? 'Logo Selected' : 'Upload Logo',
                    style: TextStyle(color: _logoImage != null ? Colors.green : null)),
                  style: OutlinedButton.styleFrom(
                    padding: const EdgeInsets.symmetric(vertical: AppSpacing.md),
                    side: BorderSide(color: _logoImage != null ? Colors.green : Theme.of(context).colorScheme.outlineVariant),
                  ),
                ),
              ),
              const SizedBox(height: AppSpacing.md),
              Text(
                'Campus Banner',
                style: AppTextStyles.labelMedium.copyWith(fontWeight: FontWeight.bold),
              ),
              const SizedBox(height: AppSpacing.xs),
              SizedBox(
                width: double.infinity,
                child: OutlinedButton.icon(
                  onPressed: _isLoading ? null : _pickBanner,
                  icon: Icon(_bannerImage != null ? Icons.check_circle_rounded : Icons.image_outlined, 
                    color: _bannerImage != null ? Colors.green : null),
                  label: Text(_bannerImage != null ? 'Banner Selected' : 'Upload Banner',
                    style: TextStyle(color: _bannerImage != null ? Colors.green : null)),
                  style: OutlinedButton.styleFrom(
                    padding: const EdgeInsets.symmetric(vertical: AppSpacing.md),
                    side: BorderSide(color: _bannerImage != null ? Colors.green : Theme.of(context).colorScheme.outlineVariant),
                  ),
                ),
              ),
              const SizedBox(height: AppSpacing.xl),
              Row(
                mainAxisAlignment: MainAxisAlignment.end,
                children: [
                  TextButton(
                    onPressed: _isLoading ? null : () => Navigator.pop(context),
                    child: const Text('Cancel'),
                  ),
                  const SizedBox(width: AppSpacing.md),
                  ElevatedButton(
                    onPressed: _isLoading ? null : _submit,
                    style: ElevatedButton.styleFrom(
                      backgroundColor: AppColors.primary,
                      foregroundColor: Colors.white,
                      padding: const EdgeInsets.symmetric(horizontal: AppSpacing.xl, vertical: AppSpacing.md),
                    ),
                    child: _isLoading 
                      ? const SizedBox(height: 20, width: 20, child: FlickrLoader())
                      : const Text('Create Campus'),
                  ),
                ],
              ),
            ],
          ),
        ),
      ),
    );
  }
}
