// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB33febtFphPq4moae54MrMOxkseHkZMXI',
    appId: '1:214610674575:web:5f26cece1aa087394301fa',
    messagingSenderId: '214610674575',
    projectId: 'vouch-push-notif',
    authDomain: 'vouch-push-notif.firebaseapp.com',
    storageBucket: 'vouch-push-notif.firebasestorage.app',
    measurementId: 'G-MWWWNKT1ZF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBuHh7J1Kkjj94xkrAipYlN8YB6lcXbuY0',
    appId: '1:214610674575:android:90795293d255e6e54301fa',
    messagingSenderId: '214610674575',
    projectId: 'vouch-push-notif',
    storageBucket: 'vouch-push-notif.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAyvRQX2miSRyxdGigXLrpPbER9LYgh07g',
    appId: '1:214610674575:ios:a7c063cf6a65eb444301fa',
    messagingSenderId: '214610674575',
    projectId: 'vouch-push-notif',
    storageBucket: 'vouch-push-notif.firebasestorage.app',
    iosBundleId: 'com.example.vouchV2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAyvRQX2miSRyxdGigXLrpPbER9LYgh07g',
    appId: '1:214610674575:ios:a7c063cf6a65eb444301fa',
    messagingSenderId: '214610674575',
    projectId: 'vouch-push-notif',
    storageBucket: 'vouch-push-notif.firebasestorage.app',
    iosBundleId: 'com.example.vouchV2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB33febtFphPq4moae54MrMOxkseHkZMXI',
    appId: '1:214610674575:web:004fa7dfc80504b14301fa',
    messagingSenderId: '214610674575',
    projectId: 'vouch-push-notif',
    authDomain: 'vouch-push-notif.firebaseapp.com',
    storageBucket: 'vouch-push-notif.firebasestorage.app',
    measurementId: 'G-VSLFBWTWW9',
  );
}
