class RouteNames {
  RouteNames._();

  static const String login = 'login';
  static const String register = 'register';
  static const String forgotPassword = 'forgot-password';
  static const String dashboard = 'dashboard';
  static const String organizations = 'organizations';
  static const String organizationDetails = 'organization-details';
  static const String events = 'events';
  static const String fees = 'fees';
  static const String attendance = 'attendance';
  static const String elections = 'elections';
  static const String finance = 'finance';
  static const String announcements = 'announcements';
  static const String activityCard = 'activity-card';
  static const String profile = 'profile';
  static const String emailVerification = 'email-verification';
  static const String resetPassword = 'reset-password';
  static const String changeEmail = 'change-email';
  static const String changePassword = 'change-password';
  static const String superAdminDashboard = 'super-admin-dashboard';
  static const String academicStructure = 'academic-structure';
  static const String campuses = 'campuses';
  static const String campusDetails = 'campus-details';
  static const String faculties = 'faculties';
  static const String facultyDetails = 'faculty-details';
  static const String programs = 'programs';
  static const String programDetails = 'program-details';
  static const String users = 'users';
  static const String officers = 'officers';
  static const String userDetails = 'user-details';
  static const String comselecDashboard = 'comselec-dashboard';
  static const String comselecElections = 'comselec-elections';
  static const String comselecCandidates = 'comselec-candidates';
  static const String comselecVoters = 'comselec-voters';
  static const String comselecResults = 'comselec-results';
  static const String comselecAnalytics = 'comselec-analytics';
  static const String comselecOfficials = 'comselec-officials';
}
